"""
Layer 8: Event Bus
==================
Structured event-driven communication layer with trace_id support
for end-to-end debugging and replay capabilities.
"""

import os
import json
import uuid
import time
import threading
from enum import Enum
from dataclasses import dataclass, asdict, field
from typing import Dict, Any, Optional, List, Callable
from datetime import datetime
from collections import defaultdict
from loguru import logger

import redis


class EventJSONEncoder(json.JSONEncoder):
    """Custom JSON encoder that handles datetime objects."""
    def default(self, o):
        if isinstance(o, datetime):
            return o.isoformat()
        return super().default(o)


class EventType(Enum):
    """System event types organized by layer."""
    # Layer 1: Data & Connectivity
    MARKET_DATA_UPDATE = "layer1:market_data_update"
    DATA_CONNECTION_STATUS = "layer1:data_connection_status"
    
    # Layer 2: Risk Management
    RISK_CHECK_PERFORMED = "layer2:risk_check_performed"
    RISK_LIMIT_BREACH = "layer2:risk_limit_breach"
    CIRCUIT_BREAKER_TRIGGERED = "layer2:circuit_breaker_triggered"
    EMERGENCY_STOP_ACTIVATED = "layer2:emergency_stop_activated"
    
    # Layer 3: Signal Generation
    SIGNAL_GENERATED = "layer3:signal_generated"
    SIGNAL_AGGREGATED = "layer3:signal_aggregated"
    VALIDATION_PASSED = "layer3:validation_passed"
    VALIDATION_FAILED = "layer3:validation_failed"
    
    # Layer 4: Intelligence
    REGIME_DETECTED = "layer4:regime_detected"
    INTELLIGENCE_VALIDATION = "layer4:intelligence_validation"
    MODEL_PREDICTION = "layer4:model_prediction"
    SELF_LEARNING_UPDATE = "layer4:self_learning_update"
    
    # Layer 5: Execution
    ORDER_EXECUTED = "layer5:order_executed"
    ORDER_FAILED = "layer5:order_failed"
    POSITION_UPDATED = "layer5:position_updated"
    LEVERAGE_ADJUSTED = "layer5:leverage_adjusted"
    
    # Layer 6: Orchestration
    HEALTH_CHECK_PERFORMED = "layer6:health_check_performed"
    HEALTH_ALERT = "layer6:health_alert"
    AUTO_RESTART_TRIGGERED = "layer6:auto_restart_triggered"
    HEALING_ACTION_TRIGGERED = "layer6:healing_action_triggered"
    HEALING_ACTION_COMPLETED = "layer6:healing_action_completed"
    CONFIG_RELOADED = "layer6:config_reloaded"
    WORKFLOW_PHASE_ADVANCED = "layer6:workflow_phase_advanced"
    WORKFLOW_STATUS_UPDATED = "layer6:workflow_status_updated"
    
    # Layer 7: Command & Control
    COMMAND_RECEIVED = "layer7:command_received"
    TELEGRAM_MESSAGE_SENT = "layer7:telegram_message_sent"
    DASHBOARD_UPDATE = "layer7:dashboard_update"
    
    # System Events
    SYSTEM_STARTUP = "system:startup"
    SYSTEM_SHUTDOWN = "system:shutdown"
    SYSTEM_ERROR = "system:error"


@dataclass
class BaseEvent:
    """Base event class with trace_id and timestamp."""
    event_type: EventType
    trace_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: float = field(default_factory=time.time)
    source_layer: Optional[int] = None
    correlation_id: Optional[str] = None  # For grouping related events
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert event to dictionary for serialization."""
        data = asdict(self)
        data['event_type'] = self.event_type.value
        data['timestamp'] = self.timestamp
        return data
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'BaseEvent':
        """Create event from dictionary - only includes BaseEvent fields."""
        data_copy = data.copy()
        if 'event_type' in data_copy and isinstance(data_copy['event_type'], str):
            data_copy['event_type'] = EventType(data_copy['event_type'])
        
        # Extract only BaseEvent fields
        base_fields = ['event_type', 'trace_id', 'timestamp', 'source_layer', 'correlation_id']
        filtered_data = {k: v for k, v in data_copy.items() if k in base_fields}
        return cls(**filtered_data)


@dataclass
class MarketDataUpdateEvent(BaseEvent):
    """Market data update from Layer 1."""
    symbol: str = ""
    price: float = 0.0
    volume: float = 0.0
    timestamp_ms: int = 0
    data: Dict[str, Any] = field(default_factory=dict)
    
    def __post_init__(self):
        if self.source_layer is None:
            self.source_layer = 1


@dataclass
class RiskCheckEvent(BaseEvent):
    """Risk check performed by Layer 2."""
    capital: float = 0.0
    daily_pnl: float = 0.0
    positions: Dict[str, Any] = field(default_factory=dict)
    risk_score: float = 0.0
    allowed: bool = True
    reason: Optional[str] = None
    
    def __post_init__(self):
        if self.source_layer is None:
            self.source_layer = 2


@dataclass
class SignalGeneratedEvent(BaseEvent):
    """Trading signal generated by Layer 3."""
    symbol: str = ""
    action: str = "HOLD"  # BUY, SELL, HOLD
    confidence: float = 0.0
    indicators: Dict[str, float] = field(default_factory=dict)
    
    def __post_init__(self):
        if self.source_layer is None:
            self.source_layer = 3


@dataclass
class RegimeDetectedEvent(BaseEvent):
    """Market regime detected by Layer 4."""
    regime: str = "sideways"  # bull, bear, volatile, sideways
    confidence: float = 0.0
    lookback_bars: int = 0
    
    def __post_init__(self):
        if self.source_layer is None:
            self.source_layer = 4


@dataclass
class OrderExecutedEvent(BaseEvent):
    """Order executed by Layer 5."""
    symbol: str = ""
    action: str = ""  # BUY, SELL
    quantity: float = 0.0
    price: float = 0.0
    order_id: str = ""
    leverage: int = 1
    
    def __post_init__(self):
        if self.source_layer is None:
            self.source_layer = 5


@dataclass
class HealthCheckEvent(BaseEvent):
    """Health check performed by Layer 6."""
    component: str = ""
    status: str = "healthy"  # healthy, degraded, unhealthy
    checks: Dict[str, str] = field(default_factory=dict)
    
    def __post_init__(self):
        if self.source_layer is None:
            self.source_layer = 6


@dataclass
class HealthAlertEvent(BaseEvent):
    """Health alert triggered by Layer 6."""
    component: str = ""
    status: str = "unhealthy"
    failure_count: int = 0
    critical: bool = False
    alert_data: Dict[str, Any] = field(default_factory=dict)
    
    def __post_init__(self):
        if self.source_layer is None:
            self.source_layer = 6


@dataclass
class HealingActionEvent(BaseEvent):
    """Healing action triggered/completed by Layer 6."""
    action: str = ""
    layer_id: str = ""
    reason: str = ""
    success: bool = False
    duration_ms: float = 0.0
    
    def __post_init__(self):
        if self.source_layer is None:
            self.source_layer = 6


@dataclass
class CommandReceivedEvent(BaseEvent):
    """Command received by Layer 7."""
    command: str = ""
    source: str = ""  # telegram, dashboard, api
    parameters: Dict[str, Any] = field(default_factory=dict)
    
    def __post_init__(self):
        if self.source_layer is None:
            self.source_layer = 7


@dataclass
class SelfLearningUpdateEvent(BaseEvent):
    """Self-learning model retrained or updated."""
    retrain_count: int = 0
    buffer_size: int = 0
    model_accuracy: float = 0.0
    decision_tree_trained: bool = False
    
    def __post_init__(self):
        if self.source_layer is None:
            self.source_layer = 4


@dataclass
class ModelPredictionEvent(BaseEvent):
    """Ensemble model prediction with per-model votes."""
    ensemble_action: str = "hold"
    confidence: float = 0.0
    regime: str = "sideways"
    decision_tree_vote: str = ""
    self_learning_vote: str = ""
    rl_vote: str = ""
    base_signal: str = ""
    
    def __post_init__(self):
        if self.source_layer is None:
            self.source_layer = 4


class EventBus:
    """
    Redis-based event bus with typed events and trace_id support.
    Provides publish/subscribe capabilities with event replay functionality.
    Thread-safe: all subscriber operations protected by RLock.
    """
    
    REDIS_HOST = os.environ.get("REDIS_HOST", "localhost")
    REDIS_PORT = int(os.environ.get("REDIS_PORT", "6379"))
    
    def __init__(self, redis_host: str = None, redis_port: int = None):
        self.redis_host = redis_host or self.REDIS_HOST
        self.redis_port = redis_port or self.REDIS_PORT
        self.redis_client: Optional[redis.Redis] = None
        self._subscribers: Dict[str, List[Callable]] = defaultdict(list)
        self._lock = threading.RLock()
        self._running = False
        self._listener_thread: Optional[threading.Thread] = None
        
        # Event storage for replay (last 1000 events per type) — always initialized
        self._memory_store: List[Dict] = []
        self.event_history_key = "fo:event_history"
        
        self._connect()
    
    def _connect(self) -> bool:
        """Connect to Redis."""
        try:
            self.redis_client = redis.Redis(
                host=self.redis_host,
                port=self.redis_port,
                decode_responses=True,
                socket_connect_timeout=5,
                socket_keepalive=True
            )
            self.redis_client.ping()
            logger.info(f"EventBus connected to Redis at {self.redis_host}:{self.redis_port}")
            return True
        except Exception as e:
            logger.warning(f"EventBus Redis connection failed: {e}. Using in-memory mode.")
            self.redis_client = None
            # Use in-memory storage as fallback
            self._memory_store: List[Dict] = []
            return False
    
    def disconnect(self):
        """Disconnect from Redis."""
        self._running = False
        if self._listener_thread:
            self._listener_thread.join(timeout=5)
        if self.redis_client:
            try:
                self.redis_client.close()
            except Exception:
                pass
            logger.info("EventBus disconnected from Redis")
    
    def publish(self, event: BaseEvent) -> bool:
        """
        Publish an event to the event bus.
        Returns True if successful, False otherwise.
        """
        try:
            event_dict = event.to_dict()
            event_data = json.dumps(event_dict, cls=EventJSONEncoder)
            
            # Add to event history for replay
            history_entry = {
                "trace_id": event.trace_id,
                "event_type": event.event_type.value,
                "timestamp": event.timestamp,
                "data": event_data
            }
            
            if self.redis_client:
                try:
                    # Add to Redis list (keep last 1000 events)
                    self.redis_client.lpush(self.event_history_key, event_data)
                    self.redis_client.ltrim(self.event_history_key, 0, 999)
                    
                    # Publish to channel for subscribers
                    channel = f"fo:event:{event.event_type.value}"
                    self.redis_client.publish(channel, event_data)
                except Exception as e:
                    logger.error(f"Redis publish error: {e}")
                    # Fall back to memory store
                    self._memory_store.append(history_entry)
                    if len(self._memory_store) > 1000:
                        self._memory_store = self._memory_store[:1000]
            else:
                # Use in-memory storage
                self._memory_store.append(history_entry)
                if len(self._memory_store) > 1000:
                    self._memory_store = self._memory_store[:1000]
            
            # Call local subscribers immediately (synchronous dispatch)
            channel = f"fo:event:{event.event_type.value}"
            with self._lock:
                subscribers = list(self._subscribers.get(channel, []))
            
            # Process all subscribers in threads to prevent blocking
            for i, callback in enumerate(subscribers):
                try:
                    import threading
                    result_holder = [None]
                    exception_holder: List[Optional[Exception]] = [None]
                    
                    def run_callback():
                        try:
                            result_holder[0] = callback(event)
                        except Exception as e:
                            exception_holder[0] = e
                    
                    t = threading.Thread(target=run_callback, daemon=True)
                    t.start()
                    t.join(timeout=5)
                    
                    if t.is_alive():
                        logger.warning(f"Callback {i} timed out after 5s")
                    elif exception_holder[0]:
                        raise exception_holder[0]
                except Exception as e:
                    logger.error(f"Error in callback {i}: {e}")
            
            return True
        
        except Exception as e:
            logger.error(f"Failed to publish event: {e}")
            return False
    
    def subscribe(self, event_types: List[EventType], callback: Callable) -> bool:
        """
        Subscribe to specific event types.
        Callback receives the deserialized event object.
        Thread-safe: subscriber registration protected by lock.
        """
        try:
            with self._lock:
                for event_type in event_types:
                    channel = f"fo:event:{event_type.value}"
                    self._subscribers[channel].append(callback)
                
                should_start = not self._running and self.redis_client
                if should_start:
                    self._running = True
            
            if should_start:
                self._listener_thread = threading.Thread(target=self._listen_loop, daemon=True)
                self._listener_thread.start()
            
            logger.info(f"Subscribed to {[et.value for et in event_types]}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to subscribe to events: {e}")
            return False
    
    def _listen_loop(self):
        """Listen for events from Redis in background thread."""
        if not self.redis_client:
            return
        
        pubsub = self.redis_client.pubsub()
        
        with self._lock:
            channels = [ch for ch in self._subscribers.keys()]
        if channels:
            try:
                pubsub.subscribe(*channels)
            except Exception as e:
                logger.error(f"Failed to subscribe to Redis channels: {e}")
                return
        
        try:
            while self._running:
                try:
                    message = pubsub.get_message(ignore_subscribe_messages=True, timeout=1.0)
                    if message and message['type'] == 'message':
                        channel = message['channel']
                        data = message['data']
                        
                        try:
                            event_dict = json.loads(data)
                            event = BaseEvent.from_dict(event_dict)
                            
                            with self._lock:
                                callbacks = list(self._subscribers.get(channel, []))
                            for callback in callbacks:
                                try:
                                    callback(event)
                                except Exception as e:
                                    logger.error(f"Event callback error: {e}")
                                        
                        except json.JSONDecodeError as e:
                            logger.error(f"Failed to deserialize event: {e}")
                            
                except Exception as e:
                    logger.error(f"Error in event listener: {e}")
                    time.sleep(1)
                    
        except Exception as e:
            logger.error(f"Event listener stopped: {e}")
        finally:
            try:
                pubsub.unsubscribe()
                pubsub.close()
            except Exception:
                pass
    
    def get_event_by_trace_id(self, trace_id: str) -> Optional[BaseEvent]:
        """Retrieve an event by its trace_id for replay/debugging."""
        try:
            if self.redis_client:
                # Search through history (this is O(n) but acceptable for 1000 events)
                events = self.redis_client.lrange(self.event_history_key, 0, -1)
                for event_data in events:
                    event_dict = json.loads(event_data)
                    if event_dict.get('trace_id') == trace_id:
                        return BaseEvent.from_dict(event_dict)
            else:
                # Search memory store
                for entry in self._memory_store:
                    if entry.get('trace_id') == trace_id:
                        return BaseEvent.from_dict(json.loads(entry['data']))
            
            return None
            
        except Exception as e:
            logger.error(f"Failed to retrieve event by trace_id: {e}")
            return None
    
    def get_events_by_type(self, event_type: EventType, limit: int = 100) -> List[BaseEvent]:
        """Get recent events of a specific type for replay/analysis."""
        try:
            events = []
            
            if self.redis_client:
                event_data_list = self.redis_client.lrange(self.event_history_key, 0, limit * 2)
                for event_data in event_data_list[:limit]:
                    event_dict = json.loads(event_data)
                    if event_dict.get('event_type') == event_type.value:
                        events.append(BaseEvent.from_dict(event_dict))
            else:
                for entry in self._memory_store[:limit]:
                    if entry.get('event_type') == event_type.value:
                        events.append(BaseEvent.from_dict(json.loads(entry['data'])))
            
            return events[:limit]
            
        except Exception as e:
            logger.error(f"Failed to get events by type: {e}")
            return []
    
    def get_events_in_time_range(self, start_time: float, end_time: float) -> List[BaseEvent]:
        """Get events within a time range for replay/analysis."""
        try:
            events = []
            
            if self.redis_client:
                event_data_list = self.redis_client.lrange(self.event_history_key, 0, 1000)
                for event_data in event_data_list:
                    event_dict = json.loads(event_data)
                    timestamp = event_dict.get('timestamp', 0)
                    if start_time <= timestamp <= end_time:
                        events.append(BaseEvent.from_dict(event_dict))
            else:
                for entry in self._memory_store:
                    if start_time <= entry.get('timestamp', 0) <= end_time:
                        events.append(BaseEvent.from_dict(json.loads(entry['data'])))
            
            return sorted(events, key=lambda e: e.timestamp)
            
        except Exception as e:
            logger.error(f"Failed to get events in time range: {e}")
            return []
    
    def get_event_count(self) -> int:
        """Get total number of events stored."""
        if self.redis_client:
            return self.redis_client.llen(self.event_history_key)
        return len(self._memory_store)
    
    def clear_history(self):
        """Clear event history."""
        if self.redis_client:
            self.redis_client.delete(self.event_history_key)
        else:
            self._memory_store.clear()
        logger.info("Event history cleared")
    
    def health_check(self) -> Dict[str, Any]:
        """Check EventBus health status."""
        status = {
            "connected": False,
            "subscriber_count": len(self._subscribers),
            "event_count": self.get_event_count(),
            "running": self._running
        }
        
        if self.redis_client:
            try:
                self.redis_client.ping()
                status["connected"] = True
            except Exception:
                status["connected"] = False
        else:
            status["connected"] = False
            status["mode"] = "in-memory"
        
        return status


# Global event bus instance
_event_bus_instance: Optional[EventBus] = None
_event_bus_lock = threading.Lock()


def get_event_bus() -> EventBus:
    """Get singleton event bus instance. Thread-safe with double-checked locking."""
    global _event_bus_instance
    if _event_bus_instance is None:
        with _event_bus_lock:
            if _event_bus_instance is None:
                _event_bus_instance = EventBus()
    return _event_bus_instance


def reset_event_bus():
    """Reset the global event bus instance."""
    global _event_bus_instance
    if _event_bus_instance:
        _event_bus_instance.disconnect()
    _event_bus_instance = None


# Convenience functions for publishing common events
def publish_market_data_update(symbol: str, price: float, volume: float, 
                              timestamp_ms: int, data: Dict[str, Any] = None):
    """Publish a market data update event."""
    event = MarketDataUpdateEvent(
        event_type=EventType.MARKET_DATA_UPDATE,
        symbol=symbol,
        price=price,
        volume=volume,
        timestamp_ms=timestamp_ms,
        data=data or {}
    )
    return get_event_bus().publish(event)


def publish_risk_check(capital: float, daily_pnl: float, positions: Dict[str, Any],
                      risk_score: float, allowed: bool, reason: str = None):
    """Publish a risk check event."""
    event = RiskCheckEvent(
        event_type=EventType.RISK_CHECK_PERFORMED,
        capital=capital,
        daily_pnl=daily_pnl,
        positions=positions,
        risk_score=risk_score,
        allowed=allowed,
        reason=reason
    )
    return get_event_bus().publish(event)


def publish_signal_generated(symbol: str, action: str, confidence: float,
                            indicators: Dict[str, float] = None):
    """Publish a signal generated event."""
    event = SignalGeneratedEvent(
        event_type=EventType.SIGNAL_GENERATED,
        symbol=symbol,
        action=action,
        confidence=confidence,
        indicators=indicators or {}
    )
    return get_event_bus().publish(event)


def publish_regime_detected(regime: str, confidence: float, lookback_bars: int):
    """Publish a regime detected event."""
    event = RegimeDetectedEvent(
        event_type=EventType.REGIME_DETECTED,
        regime=regime,
        confidence=confidence,
        lookback_bars=lookback_bars
    )
    return get_event_bus().publish(event)


def publish_order_executed(symbol: str, action: str, quantity: float,
                          price: float, order_id: str, leverage: int):
    """Publish an order executed event."""
    event = OrderExecutedEvent(
        event_type=EventType.ORDER_EXECUTED,
        symbol=symbol,
        action=action,
        quantity=quantity,
        price=price,
        order_id=order_id,
        leverage=leverage
    )
    return get_event_bus().publish(event)


def publish_health_check(component: str, status: str, 
                        checks: Dict[str, str] = None):
    """Publish a health check event."""
    event = HealthCheckEvent(
        event_type=EventType.HEALTH_CHECK_PERFORMED,
        component=component,
        status=status,
        checks=checks or {}
    )
    return get_event_bus().publish(event)


def publish_health_alert(component: str, status: str, failure_count: int,
                         critical: bool = False, alert_data: Dict[str, Any] = None):
    """Publish a health alert event."""
    event = HealthAlertEvent(
        event_type=EventType.HEALTH_ALERT,
        component=component,
        status=status,
        failure_count=failure_count,
        critical=critical,
        alert_data=alert_data or {}
    )
    return get_event_bus().publish(event)


def publish_healing_action(action: str, layer_id: str, reason: str,
                           success: bool, duration_ms: float = 0.0):
    """Publish a healing action event."""
    event = HealingActionEvent(
        event_type=EventType.HEALING_ACTION_COMPLETED,
        action=action,
        layer_id=layer_id,
        reason=reason,
        success=success,
        duration_ms=duration_ms
    )
    return get_event_bus().publish(event)


def publish_command_received(command: str, source: str,
                            parameters: Dict[str, Any] = None):
    """Publish a command received event."""
    event = CommandReceivedEvent(
        event_type=EventType.COMMAND_RECEIVED,
        command=command,
        source=source,
        parameters=parameters or {}
    )
    return get_event_bus().publish(event)


def publish_self_learning_update(retrain_count: int, buffer_size: int,
                                  model_accuracy: float = 0.0,
                                  decision_tree_trained: bool = False):
    """Publish a self-learning update event."""
    event = SelfLearningUpdateEvent(
        event_type=EventType.SELF_LEARNING_UPDATE,
        retrain_count=retrain_count,
        buffer_size=buffer_size,
        model_accuracy=model_accuracy,
        decision_tree_trained=decision_tree_trained,
    )
    return get_event_bus().publish(event)


def publish_model_prediction(ensemble_action: str, confidence: float,
                               regime: str, decision_tree_vote: str = "",
                               self_learning_vote: str = "", rl_vote: str = "", base_signal: str = ""):
    """Publish a model prediction event."""
    event = ModelPredictionEvent(
        event_type=EventType.MODEL_PREDICTION,
        ensemble_action=ensemble_action,
        confidence=confidence,
        regime=regime,
        decision_tree_vote=decision_tree_vote,
        self_learning_vote=self_learning_vote,
        rl_vote=rl_vote,
        base_signal=base_signal,
    )
    return get_event_bus().publish(event)


if __name__ == "__main__":
    # Test the event bus
    print("Testing EventBus...")
    
    bus = EventBus()
    
    # Test publishing an event
    event = MarketDataUpdateEvent(
        event_type=EventType.MARKET_DATA_UPDATE,
        symbol="BTCUSDT",
        price=50000.0,
        volume=100.5,
        timestamp_ms=int(time.time() * 1000)
    )
    
    success = bus.publish(event)
    print(f"Published event: {success}")
    
    # Test retrieving event
    retrieved = bus.get_event_by_trace_id(event.trace_id)
    print(f"Retrieved event: {retrieved is not None}")
    if retrieved:
        print(f"  Event type: {retrieved.event_type.value}")
        print(f"  Trace ID: {retrieved.trace_id}")
    
    # Test get events by type
    events = bus.get_events_by_type(EventType.MARKET_DATA_UPDATE, limit=5)
    print(f"Events by type: {len(events)} found")
    
    # Health check
    health = bus.health_check()
    print(f"Health check: {health}")
    
    bus.disconnect()
    print("EventBus test complete!")